# NUMPY

In [2]:
import numpy as np

Arrays

In [4]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.random.rand(5,2) # doesn't accept tuples

array([[0.85150986, 0.06100332],
       [0.14222796, 0.69011719],
       [0.69278911, 0.24867917],
       [0.54287638, 0.49051295],
       [0.35538161, 0.74666412]])

In [8]:
np.random.randint(1,50,(2,5))

array([[32, 32, 17, 23, 41],
       [26, 12, 18, 42, 11]])

Indexing and Selection

In [9]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2d[0,1:]

array([2, 3])

Operations

In [17]:
#axis 0 means accross the rows, operation of the columns
#axis 1 means accross the columns, operation of the rows 

In [14]:
arr2d.sum(axis=0)

array([12, 15, 18])

# PANDAS